name: Run Deploy to Deno Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write # Needed for auth with Deno Deploy

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install Danet CLI
        run: deno install --allow-read --allow-write --allow-run --allow-env -n danet https://deno.land/x/danet_cli/main.ts

      - name: Bundle app with danet CLI
        run: danet bundle run.ts

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: podcodar-backoffice
          entrypoint: run.js
          root: bundle
